version: "3"
services:
  student-image:
    container_name: student-container
    build: .
    volumes:
      - .:/student:ro
    ports:
      - "6060:6060"
    environment:
     - port=6060
     - MY_PHASE=dev
    env_file:
      - ./.env