version: "3"
services:
  student-image:
    container_name: student-container
    build: .
    volumes:
      - .:/student:ro
    ports:
      - "8085:8085"
    environment:
      - port=8085
      - MY_PHASE=prod
    env_file:
      - ./.env